import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./(components)/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Codetick App",
  description: "Generated by Marcus Ngugi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
